version: "3"

services:
    lit:
        container_name: lit
        hostname: lit
        image: massmux/lit:0.12.0-alpha
        restart: on-failure
        volumes:
          - ${PWD}/.lit:/root/.lit
        entrypoint: /app/entrypoint.sh
        environment:
            CHOSENPASSWORD: changeme
        ports:
          - 8443:8443

